name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache Zig global cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/zig
          key: ${{ runner.os }}-zig-${{ hashFiles('build.zig', 'build.zig.zon') }}
          restore-keys: |
            ${{ runner.os }}-zig-

      - name: Setup Zig
        uses: mlugg/setup-zig@v2.2.1
        with:
          version: 0.16.0

      - name: Run tests
        run: zig build test
